name: CI

on:
  pull_request:
    branches: [ main ]
    paths:
      - '2-todo-app-react/**'
  push:
    branches: [ main, 2-todo-app-react ]
    paths:
      - '2-todo-app-react/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 2-todo-app-react

    strategy:
      matrix:
        node-version: [20.18.0]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: '2-todo-app-react/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Build project
        run: npm run build
